### ISSUE TITLE
Failed to instantiate module when I run gulp serve

### ISSUE THREAD

**Issue by devsaik** [Swiip/generator-gulp-angular#1004]
angular-animate.js:9 Uncaught TypeError: Cannot read property 'noop' of undefined
2016-02-06 20:45:08.907 angular-touch.js:256 Uncaught SyntaxError: Unexpected end of input
2016-02-06 20:45:08.910 angular-messages.js:576 Uncaught SyntaxError: Unexpected token ILLEGAL
2016-02-06 20:45:08.988 angular.js:4470 Uncaught Error: [$injector:modulerr] Failed to instantiate module clickstream1 due to:
Error: [$injector:modulerr] Failed to instantiate module ngAnimate due to:
Error: [$injector:nomod] Module 'ngAnimate' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.4.9/$injector/nomod?p0=ngAnimate
    at http://localhost:3000/bower_components/angular/angular.js:68:12
    at http://localhost:3000/bower_components/angular/angular.js:2006:17
    at ensure (http://localhost:3000/bower_components/angular/angular.js:1930:38)
    at module (http://localhost:3000/bower_components/angular/angular.js:2004:14)
    at http://localhost:3000/bower_components/angular/angular.js:4447:22
    at forEach (http://localhost:3000/bower_components/angular/angular.js:341:20)
    at loadModules (http://localhost:3000/bower_components/angular/angular.js:4431:5)
    at http://localhost:3000/bower_components/angular/angular.js:4448:40
    at forEach (http://localhost:3000/bower_components/angular/angular.js:341:20)
    at loadModules (http://localhost:3000/bower_components/angular/angular.js:4431:5)
http://errors.angularjs.org/1.4.9/$injector/modulerr?p0=ngAnimate&p1=Error%…2F%2Flocalhost%3A3000%2Fbower_components%2Fangular%2Fangular.js%3A4431%3A5)
    at http://localhost:3000/bower_components/angular/angular.js:68:12
    at http://localhost:3000/bower_components/angular/angular.js:4470:15
    at forEach (http://localhost:3000/bower_components/angular/angular.js:341:20)
    at loadModules (http://localhost:3000/bower_components/angular/angular.js:4431:5)
    at http://localhost:3000/bower_components/angular/angular.js:4448:40
    at forEach (http://localhost:3000/bower_components/angular/angular.js:341:20)
    at loadModules (http://localhost:3000/bower_components/angular/angular.js:4431:5)
    at createInjector (http://localhost:3000/bower_components/angular/angular.js:4356:11)
    at doBootstrap (http://localhost:3000/bower_components/angular/angular.js:1677:20)
    at bootstrap (http://localhost:3000/bower_components/angular/angular.js:1698:12)
http://errors.angularjs.org/1.4.9/$injector/modulerr?p0=clickstream1&p1=Err…F%2Flocalhost%3A3000%2Fbower_components%2Fangular%2Fangular.js%3A1698%3A12)

**Comment by devsaik** [comment]
{
  "generator-gulp-angular": {
    "version": "1.0.2",
    "props": {
      "angularVersion": "~1.4.2",
      "angularModules": [
        {
          "key": "animate",
          "module": "ngAnimate"
        },
        {
          "key": "cookies",
          "module": "ngCookies"
        },
        {
          "key": "touch",
          "module": "ngTouch"
        },
        {
          "key": "sanitize",
          "module": "ngSanitize"
        },
        {
          "key": "messages",
          "module": "ngMessages"
        },
        {
          "key": "aria",
          "module": "ngAria"
        }
      ],
      "jQuery": {
        "key": "jquery2"
      },
      "resource": {
        "key": "angular-resource",
        "module": "ngResource"
      },
      "router": {
        "key": "ui-router",
        "module": "ui.router"
      },
      "ui": {
        "key": "bootstrap",
        "module": null
      },
      "bootstrapComponents": {
        "key": "ui-bootstrap",
        "module": "ui.bootstrap"
      },
      "cssPreprocessor": {
        "key": "stylus",
        "extension": "styl"
      },
      "jsPreprocessor": {
        "key": "noJsPrepro",
        "extension": "js",
        "srcExtension": "js"
      },
      "htmlPreprocessor": {
        "key": "noHtmlPrepro",
        "extension": "html"
      },
      "foundationComponents": {
        "name": null,
        "version": null,
        "key": null,
        "module": null
      },
      "paths": {
        "src": "src",
        "dist": "dist",
        "e2e": "e2e",
        "tmp": ".tmp"
      }
    }
  }
}

**Comment by netfish88** [comment]
same error with @devsaik when I try to run gulp serve. 
but strange thing is it worked another project that I did few weeks ago. 

Uncaught Error: [$injector:modulerr] Failed to instantiate module ng due to:
Error: [$injector:strictdi] function($provide) is not using explicit annotation and cannot be invoked in strict mode
http://errors.angularjs.org/1.4.9/$injector/strictdi?p0=function(%24provide)
    at http://localhost:3000/bower_components/angular/angular.js:68:12
    at Function.annotate [as $$annotate] (http://localhost:3000/bower_components/angular/angular.js:3804:17)
    at Object.invoke (http://localhost:3000/bower_components/angular/angular.js:4513:36)
    at runInvokeQueue (http://localhost:3000/bower_components/angular/angular.js:4441:35)
    at http://localhost:3000/bower_components/angular/angular.js:4449:11
    at forEach (http://localhost:3000/bower_components/angular/angular.js:341:20)
    at loadModules (http://localhost:3000/bower_components/angular/angular.js:4431:5)
    at createInjector (http://localhost:3000/bower_components/angular/angular.js:4356:11)
    at doBootstrap (http://localhost:3000/bower_components/angular/angular.js:1677:20)
    at Object.angular.resumeBootstrap (http://localhost:3000/bower_components/angular/angular.js:1706:12)
http://errors.angularjs.org/1.4.9/$injector/modulerr?p0=ng&p1=Error%3A%20%5…F%2Flocalhost%3A3000%2Fbower_components%2Fangular%2Fangular.js%3A1706%3A12)

**Comment by netfish88** [comment]
Fortunately, I found the reason for my case. 
I used chrome plugins like AngularJS Inspector 0.4.5, AngularJS Batarang 0.10.5. 
when I turn off these plugins. it works. 

thanks for these guys on stackoverflow.  
http://stackoverflow.com/questions/25655510/angularjs-1-3-with-ngbp-framework-doesnt-load-in-chrome-browser-when-using-ng-s

**Comment by devsaik** [comment]
Hi @netfish88 : thanks for your reply, I resolved this issue by upgrading ui router , ngTouch, ngAnimate, ngMessages
