### ISSUE TITLE
Error with eslint missing dependencies

### ISSUE THREAD

**Issue by rajarju** [Swiip/generator-gulp-angular#1022]
Facing this issue with a project generated, even after a fresh install of the generator.
Tried different combinations on the wizard as well.

```
node_modules/eslint/lib/config/config-file.js:332
            throw e;
            ^
Error: Cannot read config package: eslint-config-airbnb
Error: Cannot find module 'eslint-config-airbnb'
```

Not sure if it's an issue with a new release of eslint.

**Comment by rajarju** [comment]
Tried installing these missing dependencies manually,

```

node_modules/gulp-eslint/node_modules/eslint/lib/config/config-file.js:332
            throw e;
            ^

Error: node_modules/eslint-config-airbnb/rules/best-practices.js:
	Configuration for rule "no-labels" is invalid:
	Value "2,[object Object]" has more items than allowed.
```

**Comment by rajarju** [comment]
Seems there is an issues with eslint/eslint#5160
Please see also: eslint/eslint#5164 (PR eslint/eslint#5191)

But this is breaking the generator.

**Comment by gnicol-bzh** [comment]
I have the same issue.

I created a new `.eslintrc` and copy/paste in it:
```json
{
  "extends": "airbnb"
}
```
Then I've installed packages as specified in [airbnb doc](https://github.com/airbnb/javascript/tree/master/linters). 

When I run eslint, I have the error:
```bat
D:\_PROJECTPATH_>gulp eslint
[12:37:06] Using gulpfile D:\_PROJECTPATH_\gulpfile.js
[12:37:06] Starting 'eslint'...
D:\_PROJECTPATH_\node_modules\gulp-eslint\node_modules\eslint\lib\config\config-file.js:332
            throw e;
                  ^
Error: D:\_PROJECTPATH_\node_modules\eslint-config-airbnb\rules\best-practices.js:
        Configuration for rule "no-labels" is invalid:
        Value "2,[object Object]" has more items than allowed.

Referenced from: D:\_PROJECTPATH_\node_modules\eslint-config-airbnb\legacy.js
Referenced from: D:\_PROJECTPATH_\node_modules\eslint-config-airbnb\base.js
Referenced from: airbnb
Referenced from: D:\_PROJECTPATH_\.eslintrc
    at validateRuleOptions (D:\_PROJECTPATH_\node_modules\gulp-eslint\node_modules\eslint\lib\config\config-validator.js:102:15)
    at D:\_PROJECTPATH_\node_modules\gulp-eslint\node_modules\eslint\lib\config\config-validator.js:148:13
    at Array.forEach (native)
    at Object.validate (D:\_PROJECTPATH_\node_modules\gulp-eslint\node_modules\eslint\lib\config\config-validator.js:147:35)
    at load (D:\_PROJECTPATH_\node_modules\gulp-eslint\node_modules\eslint\lib\config\config-file.js:390:19)
    at D:\_PROJECTPATH_\node_modules\gulp-eslint\node_modules\eslint\lib\config\config-file.js:326:36
    at Array.reduceRight (native)
    at applyExtends (D:\_PROJECTPATH_\node_modules\gulp-eslint\node_modules\eslint\lib\config\config-file.js:309:28)
    at load (D:\_PROJECTPATH_\node_modules\gulp-eslint\node_modules\eslint\lib\config\config-file.js:395:22)
    at D:\_PROJECTPATH_\node_modules\gulp-eslint\node_modules\eslint\lib\config\config-file.js:326:36
```
