### ISSUE TITLE
Error MSB4019 when generating with sass(node) and typescript

### ISSUE THREAD

**Issue by hege088** [Swiip/generator-gulp-angular#1032]
Anytime i try to generate a project with only sass(node) and typescript i get this error:

```
C:\users\mhegedues\ideaprojects\newproject\node_modules\deasync\build\deasync.vcxproj(20,3) error MSB4019: Das importierte Projekt "C:\Microsoft.Cpp.Default.props" wurde nicht gefunden. Vergewissern Sie sich, dass der Pfad in der <Import>-Deklaration korrekt und die Datei auf dem Datenträger vorhanden ist.
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\MHegedues\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp
\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\MHegedues\\AppData\\Roaming\\npm\\node_modules\\npm\\
node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\users\mhegedues\ideaprojects\newproject\node_modules\deasync
gyp ERR! node -v v5.7.0
gyp ERR! node-gyp -v v3.3.0
gyp ERR! not ok
```

and this error:

```
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\MHegedues\\AppData\\Roaming\\npm\\node_modules\\npm\\bin
\\npm-cli.js" "install"
npm ERR! node v5.7.0
npm ERR! npm  v3.7.5
npm ERR! code ELIFECYCLE

npm ERR! deasync@0.1.1 install: `node ./build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the deasync@0.1.1 install script 'node ./build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the deasync package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs deasync
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls deasync
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\users\mhegedues\ideaprojects\newproject\npm-debug.log
```

**Comment by Swiip** [comment]
Looks like a problem of native compilation of node sass on Windows. Not sure it's related to the generator.

**Comment by geoHeil** [comment]
Strangely I have the same problem on centos
