### ISSUE TITLE
Error: ENOENT: no such file or directory, lstat '..../myapp/src/app/templateCacheHtml.js'

### ISSUE THREAD

**Issue by danielrvt** [Swiip/generator-gulp-angular#1152]
Whenever I try to build my project, I get this error:

> 
> [16:03:56] gulp-inject 2 files into index.less.
> fs.js:887
>   return binding.lstat(pathModule._makeLong(path));
>                  ^
> 
> Error: ENOENT: no such file or directory, lstat '/Users/danielrvt/IdeaProjects/rztest/src/app/templateCacheHtml.js'
>     at Error (native)
>     at Object.fs.lstatSync (fs.js:887:18)
>     at DestroyableTransform.TransformStream [as _transform] (/Users/danielrvt/IdeaProjects/rztest/node_modules/gulp-header/index.js:38:12)
>     at DestroyableTransform.Transform._read (/Users/danielrvt/IdeaProjects/rztest/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:159:10)
>     at DestroyableTransform.Transform._write (/Users/danielrvt/IdeaProjects/rztest/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:147:83)
>     at doWrite (/Users/danielrvt/IdeaProjects/rztest/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:313:64)
>     at writeOrBuffer (/Users/danielrvt/IdeaProjects/rztest/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:302:5)
>     at DestroyableTransform.Writable.write (/Users/danielrvt/IdeaProjects/rztest/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:241:11)
>     at write (/Users/danielrvt/IdeaProjects/rztest/node_modules/gulp-concat/node_modules/readable-stream/lib/_stream_readable.js:623:24)
>     at flow (/Users/danielrvt/IdeaProjects/rztest/node_modules/gulp-concat/node_modules/readable-stream/lib/_stream_readable.js:632:7)
>     at DestroyableTransform.pipeOnReadable (/Users/danielrvt/IdeaProjects/rztest/node_modules/gulp-concat/node_modules/readable-stream/lib/_stream_readable.js:664:5)
>     at emitNone (events.js:80:13)
>     at DestroyableTransform.emit (events.js:179:7)
>     at emitReadable_ (/Users/danielrvt/IdeaProjects/rztest/node_modules/gulp-concat/node_modules/readable-stream/lib/_stream_readable.js:448:10)
>     at emitReadable (/Users/danielrvt/IdeaProjects/rztest/node_modules/gulp-concat/node_modules/readable-stream/lib/_stream_readable.js:444:5)
>     at readableAddChunk (/Users/danielrvt/IdeaProjects/rztest/node_modules/gulp-concat/node_modules/readable-stream/lib/_stream_readable.js:187:9)

Steps to reproduce:

1. Create a new project: yo gulp-angular
2. run gulp serve:dist

**Comment by danivek** [comment]
Duplicate #1149
