### ISSUE TITLE
How do I add a new bower module to the project

### ISSUE THREAD

**Issue by ptuanvu** [Swiip/generator-gulp-angular#1156]
I have an error when i tried to add elastic search module to my project!

Failed to instantiate module cdio due to:
Error: [$injector:modulerr] Failed to instantiate module elasticsearch due to:
Error: [$injector:nomod] Module 'elasticsearch' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.5.7/$injector/nomod?p0=elas...
    at http://localhost:3000/bower_components/angular/angular.js:68:12
    at http://localhost:3000/bower_components/angular/angular.js:2075:17
    at ensure (http://localhost:3000/bower_components/angular/angular.js:1999:38)
    at module (http://localhost:3000/bower_components/angular/angular.js:2073:14)
    at http://localhost:3000/bower_components/angular/angular.js:4608:22
    at forEach (http://localhost:3000/bower_components/angular/angular.js:321:20)
    at loadModules (http://localhost:3000/bower_components/angular/angular.js:4592:5)
    at http://localhost:3000/bower_components/angular/angular.js:4609:40
    at forEach (http://localhost:3000/bower_components/angular/angular.js:321:20)
    at loadModules (http://localhost:3000/bower_components/angular/angular.js:4592:5)
http://errors.angularjs.org/1.5.7/$injector/modulerr?p0=e...)
    at http://localhost:3000/bower_components/angular/angular.js:68:12
    at http://localhost:3000/bower_components/angular/angular.js:4631:15
    at forEach (http://localhost:3000/bower_components/angular/angular.js:321:20)
    at loadModules (http://localhost:3000/bower_components/angular/angular.js:4592:5)
    at http://localhost:3000/bower_components/angular/angular.js:4609:40
    at forEach (http://localhost:3000/bower_components/angular/angular.js:321:20)
    at loadModules (http://localhost:3000/bower_components/angular/angular.js:4592:5)
    at createInjector (http://localhost:3000/bower_components/angular/angular.js:4514:19)
    at doBootstrap (http://localhost:3000/bower_components/angular/angular.js:1751:20)
    at bootstrap (http://localhost:3000/bower_components/angular/angular.js:1772:12

**Comment by mikedidomizio** [comment]
Check to make sure that you've added `elasticsearch` as a dependency in your index.module.js file

**Comment by emersonmellado** [comment]
To add a new bower component you should use the `bower install <package>`.

Please read this page to see an example: https://github.com/elastic/bower-elasticsearch-js

After that, when you run `gulp serve` the new dependency should be loaded properly.
