### ISSUE TITLE
problem gulp build

### ISSUE THREAD

**Issue by marlncpe** [Swiip/generator-gulp-angular#219]
gulp build
[00:51:48] Using gulpfile ~/trabajos/prueba_anf/gulpfile.js
[00:51:48] Starting 'wiredep'...
[00:51:48] Starting 'scripts'...
[00:51:48] Starting 'consolidate:jade:app'...
[00:51:48] Starting 'consolidate:jade:components'...
[00:51:48] Starting 'images'...
[00:51:50] Starting 'fonts'...
[00:51:50] Starting 'misc'...
[00:51:50] Finished 'consolidate:jade:app' after 1.96 s
[00:51:50] Finished 'consolidate:jade:components' after 1.82 s
[00:51:50] Starting 'consolidate:jade'...
[00:51:50] Finished 'consolidate:jade' after 8.89 μs
[00:51:50] Starting 'consolidate'...
[00:51:50] Finished 'consolidate' after 9.28 μs
[00:51:50] Starting 'partials'...

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:988:11)
    at Process.ChildProcess._handle.onexit (child_process.js:779:34)

**Comment by coryarmbrecht** [comment]
@marlncpe , are you still having this issue?

**Comment by zckrs** [comment]
Please we need details.
Read https://github.com/Swiip/generator-gulp-angular/blob/master/CONTRIBUTING.md#issues and explain your problem

**Comment by rkeshmir** [comment]
I have same error! What detail should I tell you?
