### ISSUE TITLE
This generator is not platform independency

### ISSUE THREAD

**Issue by thinksource** [Swiip/generator-gulp-angular#234]
I generate the gulp-angular project on my windows system, 
I can run it on my local development platform,
but when I put it on my server with linux (ubuntu 14.0.4).
I can not finish the ‘serve’ task and it give me error:

```
Error: Cannot find module './lang/clone'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/root/angulargulp/node_modules/wiredep/node_modules/b
ower-config/node_modules/mout/lang.js:6:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```
my npm version on my server:
```
{
  npm: '2.1.17',
  http_parser: '1.0',
  node: '0.10.35',
  v8: '3.14.5.9',
  ares: '1.9.0-DEV',
  uv: '0.10.30',
  zlib: '1.2.8',
  modules: '11',
  openssl: '1.0.1j' }
```
I add some modules as it require in my package.json in devDependencies:
```
	"wrappy":"^1.0.0",
	"vinyl":"^0.4.6",
	"lodash":"^2.4.1",
	"lodash.defaults":"^2.4.1",
	"lodash.escape":"^2.4.1",
	"lodash._escapestringchar":"^2.4.1",
	"lodash.keys":"^2.4.1",
	"lodash.templatesettings":"^2.4.1",
	"lodash.values":"^2.4.1",
	"minimist":"^1.1.0",
	"through2":"^0.6.3",
	"duplexer2":"^0.0.2",
	"clone":"^0.2.0",
	"ordered-read-streams":"^0.1.0",
	"unique-stream":"^2.0.2",
	"event-stream":"^3.2.1",
	"glob":"^4.3.2",
	"minimatch":"^2.0.1",
	"glob2base":"^0.0.12",
	"mkdirp":"^0.5.0",
	"gaze":"^0.6.4",
	"lru-cache":"^2.5.0",
	"sigmund":"^1.0.0",
	"inherits":"^2.0.1",
	"dev-ip":"^1.0.1",
	"opn": "^1.0.0",
	"portscanner-plus":"^0.2.0",
	"ua-parser-js":"^0.7.3",
	"object-path":"^0.8.1",
	"resp-modifier":"^1.0.0",
	"eazy-logger":"^2.1.0",
	"easy-extender":"^2.2.0",
	"socket.io":"^1.2.1",
	"emitter-steward":"^0.0.1",
	"glob-watcher":"^0.0.7",
	"serve-index":"^1.6.0",
	"serve-static":"^1.8.0",
	"connect":"^3.3.4",
	"foxy":"^7.0.3",
	"browser-sync-client":"^0.5.2",
	"opt-merger":"^1.1.0",
	"vinyl-sourcemaps-apply":"^0.1.4"
```

ps: It is only happend when I select the sass option:
> Sass (Node), Node.js binding to libsass, the C version of the popular styleshe
et preprocessor, Sass.

**Comment by zckrs** [comment]
Im not sure this issue is related  to the generator.
