### ISSUE TITLE
Can't find lodash when run the generator

### ISSUE THREAD

**Issue by neoblackcap** [Swiip/generator-gulp-angular#264]
Can't find lodash when I run the generator, the generator version is v0.9.0. But the v0.8.1 is alright.
the exception was raised in app/src/utils.js, in line 4. 
Add lodash into generator-gulp-angular's package.json file fix problem.

**Comment by DarrylD** [comment]
+1 same issue

**Comment by zckrs** [comment]
Yeah I will fixes that

**Comment by zckrs** [comment]
Fixed by v0.9.1

**Comment by raphox** [comment]
Today I created a new application and got the error on "server:dist":

vagrant@vagrant-ubuntu-trusty-64 ~/Projects/ng-ppa-ui $ npm list --depth=0
ppaUi@0.0.0 /home/vagrant/Projects/ng-ppa-ui
├── browser-sync@1.7.3
├── chalk@0.5.1
├── del@0.1.3
├── gulp@3.8.10
├── gulp-angular-filesort@1.0.4
├── gulp-angular-templatecache@1.4.2
├── gulp-autoprefixer@2.0.0
├── gulp-coffee@2.2.0
├── gulp-coffeelint@0.4.0
├── gulp-consolidate@0.1.2
├── gulp-csso@0.2.9
├── gulp-filter@1.0.2
├── gulp-flatten@0.0.4
├── gulp-inject@1.0.2
├── gulp-jshint@1.9.0
├── gulp-karma@0.0.4
├── gulp-load-plugins@0.7.1
├── gulp-minify-html@0.1.8
├── gulp-ng-annotate@0.3.6
├── gulp-protractor@0.0.12
├── gulp-rename@1.2.0
├── gulp-replace@0.5.1
├── gulp-rev@2.0.1
├── gulp-rev-replace@0.3.1
├── gulp-sass@1.1.0
├── gulp-size@1.1.0
├── gulp-uglify@1.0.2
├── gulp-useref@1.0.2
├── handlebars@2.0.0
├── http-proxy@1.7.3
├── jasmine-core@2.1.3
├── jshint-stylish@1.0.0
├── karma@0.12.31
├── karma-jasmine@0.3.5
├── karma-phantomjs-launcher@0.1.4
├── lodash@2.4.1
├── main-bower-files@2.4.2
├── protractor@1.4.0
├── require-dir@0.1.0
├── uglify-save-license@0.4.1
└── wiredep@2.2.2

vagrant@vagrant-ubuntu-trusty-64 ~/Projects/ng-ppa-ui $
vagrant@vagrant-ubuntu-trusty-64 ~/Projects/ng-ppa-ui $ gulp serve:dist
[13:20:34] Using gulpfile ~/Projects/ng-ppa-ui/gulpfile.js
[13:20:34] Starting 'styles'...
[13:20:35] Starting 'scripts'...
[13:20:35] Starting 'markups'...
[13:20:35] Starting 'images'...
[13:20:35] Starting 'fonts'...
[13:20:35] Starting 'misc'...
[13:20:35] Finished 'markups' after 156 ms
[13:20:35] Starting 'partials'...
[13:20:36] 'partials' errored after 295 ms
[13:20:36] Error: Cannot find module 'lodash.bind'
  at Function.Module._resolveFilename (module.js:338:15)
  at Function.Module._load (module.js:280:25)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/home/vagrant/Projects/ng-ppa-ui/node_modules/gulp-angular-templatecache/node_modules/gulp-footer/node_modules/lodash.assign/node_modules/lodash._basecreatecallback/index.js:9:12)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/home/vagrant/Projects/ng-ppa-ui/node_modules/gulp-angular-templatecache/node_modules/gulp-footer/node_modules/lodash.assign/index.js:9:26)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/home/vagrant/Projects/ng-ppa-ui/node_modules/gulp-angular-templatecache/node_modules/gulp-footer/index.js:6:14)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/home/vagrant/Projects/ng-ppa-ui/node_modules/gulp-angular-templatecache/index.js:6:14)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.defineProperty.get (/home/vagrant/Projects/ng-ppa-ui/node_modules/gulp-load-plugins/index.js:49:18)
  at Gulp.gulp.task.gulp.src.read (/home/vagrant/Projects/ng-ppa-ui/gulp/build.js:21:13)
  at module.exports (/home/vagrant/Projects/ng-ppa-ui/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
  at Gulp.Orchestrator._runTask (/home/vagrant/Projects/ng-ppa-ui/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
  at Gulp.Orchestrator._runStep (/home/vagrant/Projects/ng-ppa-ui/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
  at /home/vagrant/Projects/ng-ppa-ui/node_modules/gulp/node_modules/orchestrator/index.js:279:18
  at finish (/home/vagrant/Projects/ng-ppa-ui/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
  at /home/vagrant/Projects/ng-ppa-ui/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:52:4
  at f (/home/vagrant/Projects/ng-ppa-ui/node_modules/gulp/node_modules/orchestrator/node_modules/end-of-stream/node_modules/once/once.js:17:25)
  at DestroyableTransform.onend (/home/vagrant/Projects/ng-ppa-ui/node_modules/gulp/node_modules/orchestrator/node_modules/end-of-stream/index.js:31:18)
  at DestroyableTransform.emit (events.js:117:20)
  at /home/vagrant/Projects/ng-ppa-ui/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:965:16
  at process._tickCallback (node.js:419:13)

[13:20:36] gulp-inject Nothing to inject into index.scss.
[13:20:36] Finished 'misc' after 448 ms
[13:20:36] Finished 'styles' after 1.38 s
[13:20:36] Finished 'fonts' after 620 ms
[13:20:36] all files 2.72 kB
[13:20:36] Finished 'scripts' after 997 ms
[13:20:36] Finished 'images' after 632 ms

**Comment by raphox** [comment]
Only works when I insert new depencies on package.json:

...
    "lodash._setbinddata": "^2.4.1",
    "lodash.bind": "^2.4.1",
    "lodash.identity": "^2.4.1",
    "lodash.support": "^2.4.1",
...
