### ISSUE TITLE
Error on 'gulp build'

### ISSUE THREAD

**Issue by coryarmbrecht** [Swiip/generator-gulp-angular#281]
It almost got through the build process, but on either `gulp build` or `gulp serve:dist` I recieve the following:

```
cw $ gulp serve:dist
[13:28:51] Using gulpfile ~/cw/gulpfile.js
[13:28:51] Starting 'styles'...
[13:29:06] Starting 'partials'...
[13:29:15] Starting 'images'...
[13:29:15] Starting 'fonts'...
[13:29:19] Starting 'misc'...
[13:29:20] Finished 'images' after 5.19 s
[13:29:20] Finished 'misc' after 637 ms
[13:29:21] Finished 'styles' after 29 s
[13:29:21] Starting 'inject'...
[13:29:25] gulp-inject 1 files into index.html.
[13:29:25] Finished 'fonts' after 10 s
[13:29:25] Finished 'partials' after 20 s
[13:29:26] gulp-inject 18 files into index.html.
[13:29:27] Finished 'inject' after 6.68 s
[13:29:27] Starting 'html'...
[13:29:52] gulp-inject 1 files into index.html.

stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^
Error: ENOENT, no such file or directory '{cw/.tmp/app/app.css,cw/client/app/app.css}'
    at Object.fs.openSync (fs.js:427:18)
    at Object.fs.readFileSync (fs.js:284:15)
    at DestroyableTransform.<anonymous> (cw/node_modules/gulp-useref/index.js:81:61)
    at Array.forEach (native)
    at DestroyableTransform.<anonymous> (cw/node_modules/gulp-useref/index.js:70:35)
    at Array.forEach (native)
    at DestroyableTransform.<anonymous> (cw/node_modules/gulp-useref/index.js:46:36)
    at Array.forEach (native)
    at DestroyableTransform._transform (cw/node_modules/gulp-useref/index.js:43:15)
    at DestroyableTransform.Transform._read (cw/node_modules/gulp-useref/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
```

On the first Error line, it says 'cw/client/app/app.css'. I've searched all over and can't seem to find where 'client' has been set. Shouldn't 'client' be 'dist'? Currently it's preventing deployment. Thanks for any help!

**Comment by marani** [comment]
For version >= 9.0, `client` should be defined in `gulpfile.js`. It seems like you to use `yo --app-path='client'`. Please post your `.yo-rc.json` & generator version so I can try to reproduce.

**Comment by coryarmbrecht** [comment]
Thanks, @marani , that's good to know. Apparently, my last comment didn't post. 'client' is actually set in the index.html file within the 'inject' statements, for instance: `<!-- build:css({.tmp,client}) styles/app.css -->`. I didn't find it because it was glossed over due to the commenting out, and I was look everywhere else, like the gulpfile. :)

Also, this was in relation to combining a server (https://github.com/Swiip/generator-gulp-angular/issues/214), and I needed to resolve some of the differences.

Wish I could delete the issue! https://github.com/isaacs/github/issues/253

**Comment by zckrs** [comment]
@coryarmbrecht  can i close this issue ?
