### ISSUE TITLE
PhantomJS crashed by running "gulp test" command

### ISSUE THREAD

**Issue by stewones** [Swiip/generator-gulp-angular#301]
```
$ gulp test
[20:15:46] Using gulpfile /var/www/glamoux.app/gulpfile.js
[20:15:46] Starting 'scripts'...
[20:15:47] all files 4.42 kB
[20:15:47] Finished 'scripts' after 608 ms
[20:15:47] Starting 'browserify'...
[20:15:47] all files 4.54 kB
[20:15:47] Finished 'browserify' after 282 ms
[20:15:47] Starting 'test'...
[20:15:48] Starting Karma server...
INFO [karma]: Karma v0.12.31 server started at http://localhost:9876/
INFO [launcher]: Starting browser PhantomJS
INFO [PhantomJS 1.9.8 (Linux)]: Connected on socket M0ZhGGrk7oao8I6fnVxi with id 59226565
ERROR [launcher]: PhantomJS crashed.
	
INFO [launcher]: Trying to start PhantomJS again (1/2).
WARN [PhantomJS 1.9.8 (Linux)]: Disconnected (1 times), because no message in 10000 ms.


/var/www/glamoux.app/gulp/unit-tests.js:30
      throw err;
            ^
Error in plugin 'gulp-karma'
karma exited with code 1
    at done (/var/www/glamoux.app/node_modules/gulp-karma/index.js:56:30)
    at ChildProcess.<anonymous> (/var/www/glamoux.app/node_modules/gulp-karma/index.js:82:7)
    at ChildProcess.emit (events.js:98:17)
    at Process.ChildProcess._handle.onexit (child_process.js:810:12)
```

#### .yo-rc.json
```
{
  "generator-gulp-angular": {
    "props": {
      "angularVersion": "~1.3.4",
      "angularModules": [
        {
          "name": "angular-animate",
          "module": "ngAnimate"
        },
        {
          "name": "angular-cookies",
          "module": "ngCookies"
        },
        {
          "name": "angular-touch",
          "module": "ngTouch"
        },
        {
          "name": "angular-sanitize",
          "module": "ngSanitize"
        }
      ],
      "jQuery": {
        "name": null,
        "version": null
      },
      "resource": {
        "name": "angular-resource",
        "module": "ngResource"
      },
      "router": {
        "name": "angular-ui-router",
        "version": "~0.2.13",
        "module": "ui.router"
      },
      "ui": {
        "name": "angular-material",
        "version": "~0.5.1",
        "key": "angular-material",
        "module": "ngMaterial"
      },
      "cssPreprocessor": {
        "key": "node-sass",
        "extension": "scss",
        "module": "gulp-sass",
        "version": "~1.1.0"
      },
      "jsPreprocessor": {
        "key": "traceur",
        "extension": "js",
        "srcExtension": "es6",
        "module": "gulp-traceur",
        "version": "~0.14.1"
      },
      "htmlPreprocessors": [
        {
          "key": "jade",
          "consolidate": [
            "jade",
            {
              "pretty": "  "
            }
          ],
          "extension": "jade",
          "npm": {
            "jade": "~1.8.1"
          }
        }
      ],
      "bootstrapComponents": {
        "name": null,
        "version": null,
        "key": null,
        "module": null
      },
      "foundationComponents": {
        "name": null,
        "version": null,
        "key": null,
        "module": null
      }
    }
  }
}
```

**Comment by Swiip** [comment]
First of all, you should update the generator because your version is running old.

I think the problem is about Traceur. I got errors too on karma with Traceur with the current version. But I don't get the same error so I'm not sure. I also have to check why the tests missed that...

**Comment by stewones** [comment]
@Swiip yep, in the 6to5 version it run Like a boss. I chose this One. Thx.
