### ISSUE TITLE
gulp serve not working

### ISSUE THREAD

**Issue by Hesesses** [Swiip/generator-gulp-angular#310]
I had gulp serve working as it should, but suddenly getting this error:

```
[14:16:14] Using gulpfile ~/my_project/web/gulpfile.js
[14:16:14] Starting 'wiredep'...
[14:16:14] Finished 'wiredep' after 5.89 ms
[14:16:14] Starting 'styles'...

events.js:72
        throw er; // Unhandled 'error' event
              ^
TypeError: Cannot read property 'main' of undefined
    at findMainFiles (/Users/hese/my_project/web/node_modules/wiredep/lib/detect-dependencies.js:89:39)
    at /Users/hese/my_project/web/node_modules/wiredep/lib/detect-dependencies.js:151:17
    at forOwn (/Users/hese/my_project/web/node_modules/wiredep/node_modules/lodash/dist/lodash.js:2105:15)
    at Function.forEach (/Users/hese/my_project/web/node_modules/wiredep/node_modules/lodash/dist/lodash.js:3302:9)
    at detectDependencies (/Users/hese/my_project/web/node_modules/wiredep/lib/detect-dependencies.js:33:7)
    at wiredep (/Users/hese/my_project/web/node_modules/wiredep/wiredep.js:65:39)
    at DestroyableTransform._transform (/Users/hese/my_project/web/node_modules/wiredep/wiredep.js:134:34)
    at DestroyableTransform.Transform._read (/Users/hese/my_project/web/node_modules/wiredep/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/Users/hese/my_project/web/node_modules/wiredep/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/Users/hese/my_project/web/node_modules/wiredep/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
```

Any ideas how to fix this? gulp serve:dist works

**Comment by vmlf01** [comment]
Have you tried running npm install / bower install again? Maybe you are missing a dependency

**Comment by Hesesses** [comment]
I installed a new bower component and it started working.. weird

**Comment by Hesesses** [comment]
I'm working another project now and have the same error again.
When install new bower components i'm getting the error above.
bower install angular-ui-notification --save

If I uninstall the component, gulp serve works again.

Any ideas?

**Comment by zckrs** [comment]
I just try with the latest version v1.0.0-rc1 
And all works.

Can you retry ? 

[How to update my project?](https://github.com/Swiip/generator-gulp-angular/blob/master/docs/recipes/upgrade-my-current-project.md)
