### ISSUE TITLE
Src path change doesn't work correctly in build 

### ISSUE THREAD

**Issue by tirli** [Swiip/generator-gulp-angular#329]
I just generated a new project and tried to change src path as it mentioned in readme 

> All paths configuration are stored in gulpfile.js. Change gulp.paths in gulpfile.js if you want to config paths after the app is generated.

I changed src in gulpfile to 'public' and renamed my src directory also. Ordinary `gulp serve` works correctly, though when I try to run `gulp serve:dist` it fails on `html` task

Here is an error stack trace:

```
[18:51:28] Starting 'html'...
[18:51:37] gulp-inject 1 files into 404.html.
[18:51:37] gulp-inject 1 files into index.html.

stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^
Error: ENOENT, no such file or directory '{/home/kate/projects/test/.tmp/serve/components/navbar/navbar.controller.js,/home/kate/projects/test/.tmp/partials/components/navbar/navbar.controller.js,/home/kate/projects/test/src/components/navbar/navbar.controller.js}'
    at Object.fs.openSync (fs.js:439:18)
    at Object.fs.readFileSync (fs.js:290:15)
    at DestroyableTransform.<anonymous> (/home/kate/projects/test/node_modules/gulp-useref/index.js:81:61)
    at Array.forEach (native)
    at DestroyableTransform.<anonymous> (/home/kate/projects/test/node_modules/gulp-useref/index.js:70:35)
    at Array.forEach (native)
    at DestroyableTransform.<anonymous> (/home/kate/projects/test/node_modules/gulp-useref/index.js:46:36)
    at Array.forEach (native)
    at DestroyableTransform._transform (/home/kate/projects/test/node_modules/gulp-useref/index.js:43:15)
    at DestroyableTransform.Transform._read (/home/kate/projects/test/node_modules/gulp-useref/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
```

As you can see it's still trying to pick files from src directory (`/home/kate/projects/test/src/components/navbar/navbar.controller.js`) though I can't find where to fix it

**Comment by marani** [comment]
Sorry for the misleading README, actually 'most' but not all path configurations are stored in `gulp.paths`. To complete the path change after the app is generated, you will have to look into `index.html` to make paths in build comments, for example, things in `<!-- build:js...-->`

We might need to do something make these build instruction in `index.html` depends on `gulp.paths` in some way. I think it's possible but can't find time to make a PR now.

**Comment by Swiip** [comment]
There is work to do explain how everything works in order to help people tune his configuration. This is planned but nothing more right now.
