### ISSUE TITLE
After upgrading generator cant generate new projects

### ISSUE THREAD

**Issue by wgorder** [Swiip/generator-gulp-angular#350]
It fails with this error on running `yo gulp-angular`  I already tried using npm to uninstall and reinstall the generator.  Still seeing this same issue.  Is something broke in the latest release?

```
TypeError: Object #<Object> has no method 'on'
    at run (/usr/local/lib/node_modules/generator-gulp-angular/node_modules/yeoman-generator/lib/base.js:444:21)
    at Environment.run (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/environment.js:329:20)
    at /usr/local/lib/node_modules/yo/cli.js:110:9
    at Environment.resolver.lookup (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/resolver.js:49:32)
    at init (/usr/local/lib/node_modules/yo/cli.js:86:7)
    at pre (/usr/local/lib/node_modules/yo/cli.js:64:3)
    at Object.<anonymous> (/usr/local/lib/node_modules/yo/cli.js:161:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
``

**Comment by wgorder** [comment]
For the next person that runs into this upgrade yeoman

```
npm update -g npm
npm install -g yo bower grunt-cli gulp
```
