### ISSUE TITLE
Cannot find module lodash on default install

### ISSUE THREAD

**Issue by ianks** [Swiip/generator-gulp-angular#357]
After running the generator from master, I get the below error. npm installing lodash fixes things.
```
$  gulp test

Error: Cannot find module 'lodash'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/ianks/Desktop/fcquangular/gulpfile.js:5:9)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

**Comment by zckrs** [comment]
https://github.com/Swiip/generator-gulp-angular/pull/361
