### ISSUE TITLE
ReferenceError: paths is not defined on default install

### ISSUE THREAD

**Issue by ianks** [Swiip/generator-gulp-angular#359]
When attempting to run gulp serve after default install:

```
[14:07:27] ReferenceError: paths is not defined
    at Gulp.<anonymous> (/Users/ianks/Desktop/fcq/gulp/server.js:43:5)
    at module.exports (/Users/ianks/Desktop/fcq/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/ianks/Desktop/fcq/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/ianks/Desktop/fcq/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at /Users/ianks/Desktop/fcq/node_modules/gulp/node_modules/orchestrator/index.js:279:18
    at finish (/Users/ianks/Desktop/fcq/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
    at module.exports (/Users/ianks/Desktop/fcq/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:60:3)
    at Gulp.Orchestrator._runTask (/Users/ianks/Desktop/fcq/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/ianks/Desktop/fcq/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at /Users/ianks/Desktop/fcq/node_modules/gulp/node_modules/orchestrator/index.js:279:18
```

**Comment by zckrs** [comment]
Should be fixed when merge https://github.com/Swiip/generator-gulp-angular/pull/361
