### ISSUE TITLE
crash on creating new gulp-angular application

### ISSUE THREAD

**Issue by geoHeil** [Swiip/generator-gulp-angular#363]
I just updated the generator.
And now when I execute: yo gulp-angular myApp

/usr/local/lib/node_modules/generator-gulp-angular/node_modules/yeoman-generator/lib/base.js:444
  this.env.sharedFs.on('change', writeFiles);
                    ^
TypeError: undefined is not a function
    at run (/usr/local/lib/node_modules/generator-gulp-angular/node_modules/yeoman-generator/lib/base.js:444:21)
    at Environment.run (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/environment.js:319:20)
    at /usr/local/lib/node_modules/yo/lib/cli.js:87:9
    at Environment.resolver.lookup (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/resolver.js:49:32)
    at init (/usr/local/lib/node_modules/yo/lib/cli.js:66:7)
    at pre (/usr/local/lib/node_modules/yo/lib/cli.js:53:3)
    at Object.<anonymous> (/usr/local/lib/node_modules/yo/lib/cli.js:156:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)

What is wrong here?

**Comment by Swiip** [comment]
Which version of Node have you? When you say updated, you talk of master or 0.9.1?

**Comment by geoHeil** [comment]
node version: v0.12.0
(just ran brew update & brew upgrade)

**Comment by yordis** [comment]
I got the same right now. Node: v0.10.33

**Comment by Swiip** [comment]
0.9.1 or master?

**Comment by yordis** [comment]
version: 0.9.1

**Comment by geoHeil** [comment]
where can I find the gulp-angular version? I just installed it via the npm install -g generator-gulp-angular

**Comment by Swiip** [comment]
So you don't have the master version. The 0.9.1 version is perhaps not perfect but can and have worked.

Travis is currently having some trouble downloading the dependencies. Try `rm -rf node_modules && npm install`

**Comment by geoHeil** [comment]
I un-installed via npm nad re-installed via YO directly

when I start the generator I get a different error than above:

/usr/local/lib/node_modules/yo/node_modules/inquirer/node_modules/rx/dist/rx.all.js:9379
        throw e;
              ^
TypeError: undefined is not a function
    at run (/usr/local/lib/node_modules/generator-gulp-angular/node_modules/yeoman-generator/lib/base.js:444:21)
    at Environment.run (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/environment.js:319:20)
    at module.exports (/usr/local/lib/node_modules/yo/lib/routes/run.js:20:11)
    at Router.navigate (/usr/local/lib/node_modules/yo/lib/router.js:35:30)
    at PromptUI.completed (/usr/local/lib/node_modules/yo/lib/routes/home.js:76:20)
    at PromptUI.onCompletion (/usr/local/lib/node_modules/yo/node_modules/inquirer/lib/ui/prompt.js:69:10)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.completed (/usr/local/lib/node_modules/yo/node_modules/inquirer/node_modules/rx/dist/rx.all.js:1965:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/local/lib/node_modules/yo/node_modules/inquirer/node_modules/rx/dist/rx.all.js:1902:14)
    at AutoDetachObserverPrototype.completed (/usr/local/lib/node_modules/yo/node_modules/inquirer/node_modules/rx/dist/rx.all.js:9397:23)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/local/lib/node_modules/yo/node_modules/inquirer/node_modules/rx/dist/rx.all.js:1902:14)

**Comment by Swiip** [comment]
I don't reproduce, don't know where to look right now.

**Comment by yordis** [comment]
@Swiip Reinstall the packages doesn't work.

**Comment by zckrs** [comment]
I don't reproduce too

**Comment by albenesi** [comment]
You might try updating Yeoman. I was having a similar issue.

**Comment by Swiip** [comment]
I tried to reinstall almost everything, still no problems. What's your OS perhaps?

**Comment by cgaudreau** [comment]
Updating Yeoman fixed this for me.

```npm install -g yo```

**Comment by geoHeil** [comment]
seems to be the fix for me as well

**Comment by louiswilbrink** [comment]
Wanted to note that I kept getting this error until I upgraded to node 0.12.0.  I am using nvm on a yosemite machine, and made sure to upgrade yo gulp bower after upgrading node.

**Comment by hwoarangzk** [comment]
Update `yo` to the latest version would solve the problem. I just fixed this :)
