### ISSUE TITLE
gulp test fails with traceur (v0.9.1)

### ISSUE THREAD

**Issue by eseceve** [Swiip/generator-gulp-angular#386]
I run `yo gulp-angular esix` and then run `gulp test`. 
Also, I checked with **6to5** and `gulp test`works fine.

```
es6|⇒ gulp test
[12:51:03] Using gulpfile ~/src/tests/es6/gulpfile.js
[12:51:03] Starting 'scripts'...
[12:51:11] all files 4.24 kB
[12:51:11] Finished 'scripts' after 7.65 s
[12:51:11] Starting 'browserify'...
[12:51:14] all files 4.37 kB
[12:51:14] Finished 'browserify' after 3.9 s
[12:51:14] Starting 'test'...
[12:51:21] Starting Karma server...
INFO [karma]: Karma v0.12.31 server started at http://localhost:9876/
INFO [launcher]: Starting browser PhantomJS
INFO [PhantomJS 1.9.8 (Mac OS X)]: Connected on socket OmF1Jx85XNbynnytCOYX with id 84430719
PhantomJS 1.9.8 (Mac OS X) ERROR
  TypeError: 'undefined' is not a function (evaluating 'Function.prototype.call.bind(Function.prototype.apply)')
  at /Users/eseceve/src/tests/es6/bower_components/traceur-runtime/traceur-runtime.js:20



/Users/eseceve/src/tests/es6/gulp/unit-tests.js:32
      throw err;
            ^
Error in plugin 'gulp-karma'
karma exited with code 1
    at done (/Users/eseceve/src/tests/es6/node_modules/gulp-karma/index.js:56:30)
    at ChildProcess.<anonymous> (/Users/eseceve/src/tests/es6/node_modules/gulp-karma/index.js:82:7)
    at ChildProcess.emit (events.js:98:17)
    at Process.ChildProcess._handle.onexit (child_process.js:820:12)
es6|⇒
```

My .yo-rc.json file
```
{
  "generator-gulp-angular": {
    "props": {
      "paths": {
        "src": "src",
        "dist": "dist",
        "e2e": "e2e",
        "tmp": ".tmp"
      },
      "angularVersion": "~1.3.4",
      "angularModules": [
        {
          "name": "angular-animate",
          "module": "ngAnimate"
        },
        {
          "name": "angular-cookies",
          "module": "ngCookies"
        },
        {
          "name": "angular-touch",
          "module": "ngTouch"
        },
        {
          "name": "angular-sanitize",
          "module": "ngSanitize"
        }
      ],
      "jQuery": {
        "name": null,
        "version": null
      },
      "resource": {
        "name": null,
        "version": null,
        "module": null
      },
      "router": {
        "name": null,
        "version": null,
        "module": null
      },
      "ui": {
        "name": "angular-material",
        "version": "~0.5.1",
        "key": "angular-material",
        "module": "ngMaterial"
      },
      "cssPreprocessor": {
        "key": "stylus",
        "extension": "styl",
        "module": "gulp-stylus",
        "version": "~1.3.4"
      },
      "jsPreprocessor": {
        "key": "traceur",
        "extension": "js",
        "srcExtension": "es6",
        "module": "gulp-traceur",
        "version": "~0.14.1"
      },
      "htmlPreprocessor": {
        "key": "jade",
        "extension": "jade",
        "module": "jade",
        "version": "~1.8.1"
      },
      "bootstrapComponents": {
        "name": null,
        "version": null,
        "key": null,
        "module": null
      },
      "foundationComponents": {
        "name": null,
        "version": null,
        "key": null,
        "module": null
      },
      "advancedFeatures": []
    }
  }
}
```

**Comment by eseceve** [comment]
I researched about this issue and I found that [Traceur does not work in phantomjs](https://github.com/google/traceur-compiler/issues/908) because [Function.prototype.bind is undefined](https://github.com/ariya/phantomjs/issues/10522) in phantomJs **1.x** and it's fixed in **2.0** but karma-phantomjs-launcher uses phantomJs 1.9 =/.

**Comment by Swiip** [comment]
Sorry for the late answer. We should have more test with Traceur, thanks for the report. But to be honest, I'm not sure of the correction we should choose...

**Comment by eseceve** [comment]
I used **chrome** instead of **phanthomjs** and `gulp test`works fine. Also, I changed `unit-test.js`to use karma without **gulp-karma** plugin because that plugin will be deprecate and it does not support files loaded by cdn. So, here is my configuration:

karma.conf.js
```javascript
'use strict';

module.exports = function(config) {

  config.set({
    logLevel: config.LOG_INFO,
    //logLevel: config.LOG_DEBUG,

    autoWatch : true,

    frameworks: ['jasmine'],

    browsers : ['Chrome' /*, 'phantomjs'*/],

    plugins : [
      'karma-phantomjs-launcher',
      'karma-chrome-launcher',
      'karma-jasmine'
    ]
  });
};

```

<br>
gulp/unit-tests.js
```javascript
'use strict';

var $ = require('gulp-load-plugins')();
var gulp = require('gulp');
var karma = require('karma').server;
var wiredep = require('wiredep');

var paths = gulp.paths;

function runTests (singleRun, done) {
  var bowerDeps = wiredep({
    directory: 'bower_components',
    exclude: ['bootstrap-sass-official'],
    dependencies: true,
    devDependencies: true
  });

  var testFiles = bowerDeps.js.concat([
    paths.tmp + '/serve/app/index.js',
    paths.src + '/{app,components}/**/*.spec.js',
    paths.src + '/{app,components}/**/*.mock.js',
    // external files
    'http://example.com/file/from/cdn.js'
  ]);

  karma.start({
    configFile: __dirname + '/../karma.conf.js',
    files: testFiles,
    singleRun: singleRun
  }, done);
}

gulp.task('test', ['browserify'], function (done) { runTests(true, done) });
gulp.task('test:auto', ['browserify'], function (done) { runTests(false, done) });

```
