### ISSUE TITLE
ng-annotate fails on build

### ISSUE THREAD

**Issue by swamper** [Swiip/generator-gulp-angular#424]
Current version install. Nothing has been modified by me. I passed --dist-path='public' on the generator.

.yo-rc.json:

```
{
  "generator-gulp-angular": {
    "props": {
      "paths": {
        "src": "src",
        "dist": "public",
        "e2e": "e2e",
        "tmp": ".tmp"
      },
      "angularVersion": "~1.3.4",
      "angularModules": [
        {
          "name": "angular-animate",
          "module": "ngAnimate"
        },
        {
          "name": "angular-cookies",
          "module": "ngCookies"
        },
        {
          "name": "angular-touch",
          "module": "ngTouch"
        },
        {
          "name": "angular-sanitize",
          "module": "ngSanitize"
        }
      ],
      "jQuery": {
        "name": "jquery",
        "version": "~2.1.1"
      },
      "resource": {
        "name": "angular-resource",
        "module": "ngResource"
      },
      "router": {
        "name": "angular-ui-router",
        "version": "~0.2.13",
        "module": "ui.router"
      },
      "ui": {
        "name": "angular-material",
        "version": "~0.5.1",
        "key": "angular-material",
        "module": "ngMaterial"
      },
      "cssPreprocessor": {
        "key": "node-sass",
        "extension": "scss",
        "module": "gulp-sass",
        "version": "~1.1.0"
      },
      "jsPreprocessor": {
        "key": "none",
        "extension": "js",
        "srcExtension": "js",
        "module": null,
        "version": null
      },
      "htmlPreprocessor": {
        "key": "none",
        "extension": "html",
        "module": null,
        "version": null
      },
      "bootstrapComponents": {
        "name": null,
        "version": null,
        "key": null,
        "module": null
      },
      "foundationComponents": {
        "name": null,
        "version": null,
        "key": null,
        "module": null
      }
    }
  }
}
```

swamper@swampers-dev:$ gulp
[11:38:53] Using gulpfile /mnt/dev1/dev/swamper/angular/angular-build/c2/gulpfile.js
[11:38:53] Starting 'clean'...
[11:38:54] Finished 'clean' after 26 ms
[11:38:54] Starting 'default'...
[11:38:54] Starting 'styles'...
[11:38:54] Starting 'partials'...
[11:38:54] Starting 'images'...
[11:38:54] Starting 'fonts'...
[11:38:54] Starting 'misc'...
[11:38:54] Finished 'default' after 486 ms
[11:38:54] gulp-inject Nothing to inject into index.scss.
[11:38:54] Finished 'misc' after 82 ms
[11:38:54] Finished 'partials' after 291 ms
[11:38:54] Finished 'styles' after 569 ms
[11:38:54] Starting 'inject'...
[11:38:54] gulp-inject 1 files into 404.html.
[11:38:54] gulp-inject 1 files into index.html.
[11:38:54] gulp-inject 3 files into 404.html.
[11:38:54] gulp-inject 3 files into index.html.
[11:38:54] Finished 'inject' after 143 ms
[11:38:54] Starting 'html'...
[11:38:55] Finished 'fonts' after 684 ms
[11:38:55] gulp-inject 1 files into 404.html.
[11:38:55] gulp-inject 1 files into index.html.
/mnt/dev1/dev/swamper/angular/angular-build/c2/node_modules/gulp-ng-annotate/node_modules/ng-annotate/build/es5/ng-annotate-main.js:330
    target.$methodName = method.name;
                       ^
TypeError: Cannot assign to read only property '$methodName' of false
    at matchRegular (/mnt/dev1/dev/swamper/angular/angular-build/c2/node_modules/gulp-ng-annotate/node_modules/ng-annotate/build/es5/ng-annotate-main.js:330:24)
    at match (/mnt/dev1/dev/swamper/angular/angular-build/c2/node_modules/gulp-ng-annotate/node_modules/ng-annotate/build/es5/ng-annotate-main.js:36:66)
    at traverse.post (/mnt/dev1/dev/swamper/angular/angular-build/c2/node_modules/gulp-ng-annotate/node_modules/ng-annotate/build/es5/ng-annotate-main.js:995:23)
    at visit (/mnt/dev1/dev/swamper/angular/angular-build/c2/node_modules/gulp-ng-annotate/node_modules/ng-annotate/node_modules/ordered-ast-traverse/ordered-ast-traverse.js:50:13)
    at visit (/mnt/dev1/dev/swamper/angular/angular-build/c2/node_modules/gulp-ng-annotate/node_modules/ng-annotate/node_modules/ordered-ast-traverse/ordered-ast-traverse.js:44:21)
    at visit (/mnt/dev1/dev/swamper/angular/angular-build/c2/node_modules/gulp-ng-annotate/node_modules/ng-annotate/node_modules/ordered-ast-traverse/ordered-ast-traverse.js:41:25)
    at visit (/mnt/dev1/dev/swamper/angular/angular-build/c2/node_modules/gulp-ng-annotate/node_modules/ng-annotate/node_modules/ordered-ast-traverse/ordered-ast-traverse.js:44:21)
    at visit (/mnt/dev1/dev/swamper/angular/angular-build/c2/node_modules/gulp-ng-annotate/node_modules/ng-annotate/node_modules/ordered-ast-traverse/ordered-ast-traverse.js:41:25)
    at visit (/mnt/dev1/dev/swamper/angular/angular-build/c2/node_modules/gulp-ng-annotate/node_modules/ng-annotate/node_modules/ordered-ast-traverse/ordered-ast-traverse.js:44:21)
    at visit (/mnt/dev1/dev/swamper/angular/angular-build/c2/node_modules/gulp-ng-annotate/node_modules/ng-annotate/node_modules/ordered-ast-traverse/ordered-ast-traverse.js:41:25)

Build fails.

I then updated all npm and bower packages to latest versions and ran gulp after. Build passes and gulp serve will serve and display the page correctly. The files in the /.tmp directory are correct. However....

I get this in /public/index.html:

```
<!doctype html><html class="no-js" ng-app="c2"><head><meta charset="utf-8"><title>c2</title><meta name="description" content=""><meta name="viewport" content="width=device-width"><link rel="stylesheet" href="styles/vendor-c399327d.css"><link rel="stylesheet" href="styles/app-ae7767ab.css"></head><body><div ui-view=""></div><script>
      (function(b,o,i,l,e,r){b.GoogleAnalyticsObject=l;b[l]||(b[l]=
      function(){(b[l].q=b[l].q||[]).push(arguments)});b[l].l=+new Date;
      e=o.createElement(i);r=o.getElementsByTagName(i)[0];
      e.src='//www.google-analytics.com/analytics.js';
      r.parentNode.insertBefore(e,r)}(window,document,'script','ga'));
      ga('create','UA-XXXXX-X');ga('send','pageview');
    </script><script src="scripts/vendor-4d69fe19.js"></script><script src="scripts/app-246d12db.js"></script></body></html>
```
swamper@swampers-dev:$ gulp test
[13:23:05] Using gulpfile /mnt/dev1/dev/swamper/angular/angular-build/c2/gulpfile.js
[13:23:05] Starting 'test'...
[13:23:06] Starting Karma server...
INFO [karma]: Karma v0.12.31 server started at http://localhost:9876/
INFO [launcher]: Starting browser PhantomJS
INFO [PhantomJS 1.9.8 (Linux)]: Connected on socket anxzVooxLsmFN3qWYCEJ with id 57977780
PhantomJS 1.9.8 (Linux): Executed 1 of 1 SUCCESS (0.002 secs / 0.018 secs)

swamper@swampers-dev:$ gulp protractor
[13:23:57] Using gulpfile /mnt/dev1/dev/swamper/angular/angular-build/c2/gulpfile.js
[13:23:57] Starting 'styles'...
[13:23:58] Starting 'webdriver-update'...
[13:23:58] gulp-inject Nothing to inject into index.scss.
[13:23:58] Finished 'styles' after 351 ms
[13:23:58] Starting 'inject'...
[13:23:58] gulp-inject 1 files into 404.html.
[13:23:58] gulp-inject 1 files into index.html.
selenium standalone is up to date.
chromedriver is up to date.
[13:23:58] gulp-inject 3 files into 404.html.
[13:23:58] gulp-inject 3 files into index.html.
[13:23:58] Finished 'webdriver-update' after 171 ms
[13:23:58] Finished 'inject' after 110 ms
[13:23:58] Starting 'serve:e2e'...
[13:23:58] 'serve:e2e' errored after 13 ms
[13:23:58] TypeError: Cannot read property 'map' of null
    at Object.opts.callbacks.files (/mnt/dev1/dev/swamper/angular/angular-build/c2/node_modules/browser-sync/lib/cli/cli-options.js:252:39)
    at /mnt/dev1/dev/swamper/angular/angular-build/c2/node_modules/browser-sync/lib/cli/cli-options.js:271:54
    at /mnt/dev1/dev/swamper/angular/angular-build/c2/node_modules/browser-sync/node_modules/immutable/dist/immutable.js:1131:46
    at /mnt/dev1/dev/swamper/angular/angular-build/c2/node_modules/browser-sync/node_modules/immutable/dist/immutable.js:1864:16
    at ValueNode.iterate (/mnt/dev1/dev/swamper/angular/angular-build/c2/node_modules/browser-sync/node_modules/immutable/dist/immutable.js:2231:12)
    at BitmapIndexedNode.iterate.HashArrayMapNode.iterate [as iterate] (/mnt/dev1/dev/swamper/angular/angular-build/c2/node_modules/browser-sync/node_modules/immutable/dist/immutable.js:2224:24)
    at HashArrayMapNode.BitmapIndexedNode.iterate.HashArrayMapNode.iterate [as iterate] (/mnt/dev1/dev/swamper/angular/angular-build/c2/node_modules/browser-sync/node_modules/immutable/dist/immutable.js:2224:24)
    at src_Map__Map.__iterate (/mnt/dev1/dev/swamper/angular/angular-build/c2/node_modules/browser-sync/node_modules/immutable/dist/immutable.js:1862:32)
    at KeyedIterable.mappedSequence.__iterateUncached (/mnt/dev1/dev/swamper/angular/angular-build/c2/node_modules/browser-sync/node_modules/immutable/dist/immutable.js:1130:23)
    at seqIterate (/mnt/dev1/dev/swamper/angular/angular-build/c2/node_modules/browser-sync/node_modules/immutable/dist/immutable.js:593:16)

 I'm no coder. I hack at it. Any thoughts on where I need to go with this? Me and angular just started getting friendly and we still have major break downs in communication from time to time. I will however attempt anything. If the issue has been answered just point me to it I just failed to find it. Thanks.

**Comment by oblogic7** [comment]
Can confirm that build is failing with the same error.

```
/usr/local/bin/node /usr/local/lib/node_modules/gulp/bin/gulp.js --color --gulpfile /Users/matt/PhpstormProjects/test-project/gulpfile.js build
[09:34:31] Using gulpfile ~/PhpstormProjects/test-project/gulpfile.js
[09:34:31] Starting 'styles'...
[09:34:32] Starting 'partials'...
[09:34:32] Starting 'images'...
[09:34:32] Starting 'fonts'...
[09:34:32] Starting 'misc'...
[09:34:32] gulp-inject Nothing to inject into index.scss.
[09:34:32] Finished 'misc' after 107 ms
[09:34:32] Finished 'partials' after 347 ms
[09:34:32] Finished 'fonts' after 193 ms
[09:34:32] Finished 'images' after 197 ms
[09:34:32] Finished 'styles' after 918 ms
[09:34:32] Starting 'inject'...
[09:34:32] gulp-inject 1 files into 404.html.
[09:34:32] gulp-inject 1 files into index.html.
[09:34:32] gulp-inject 3 files into 404.html.
[09:34:32] gulp-inject 3 files into index.html.
[09:34:32] Finished 'inject' after 194 ms
[09:34:32] Starting 'html'...
[09:34:33] gulp-inject 1 files into 404.html.
[09:34:33] gulp-inject 1 files into index.html.
/Users/matt/PhpstormProjects/test-project/node_modules/gulp-ng-annotate/node_modules/ng-annotate/build/es5/ng-annotate-main.js:330
    target.$methodName = method.name;
                       ^
TypeError: Cannot assign to read only property '$methodName' of false
    at matchRegular (/Users/matt/PhpstormProjects/test-project/node_modules/gulp-ng-annotate/node_modules/ng-annotate/build/es5/ng-annotate-main.js:330:24)
    at match (/Users/matt/PhpstormProjects/test-project/node_modules/gulp-ng-annotate/node_modules/ng-annotate/build/es5/ng-annotate-main.js:36:66)
    at traverse.post (/Users/matt/PhpstormProjects/test-project/node_modules/gulp-ng-annotate/node_modules/ng-annotate/build/es5/ng-annotate-main.js:995:23)
    at visit (/Users/matt/PhpstormProjects/test-project/node_modules/gulp-ng-annotate/node_modules/ng-annotate/node_modules/ordered-ast-traverse/ordered-ast-traverse.js:50:13)
    at visit (/Users/matt/PhpstormProjects/test-project/node_modules/gulp-ng-annotate/node_modules/ng-annotate/node_modules/ordered-ast-traverse/ordered-ast-traverse.js:44:21)
    at visit (/Users/matt/PhpstormProjects/test-project/node_modules/gulp-ng-annotate/node_modules/ng-annotate/node_modules/ordered-ast-traverse/ordered-ast-traverse.js:41:25)
    at visit (/Users/matt/PhpstormProjects/test-project/node_modules/gulp-ng-annotate/node_modules/ng-annotate/node_modules/ordered-ast-traverse/ordered-ast-traverse.js:44:21)
    at visit (/Users/matt/PhpstormProjects/test-project/node_modules/gulp-ng-annotate/node_modules/ng-annotate/node_modules/ordered-ast-traverse/ordered-ast-traverse.js:41:25)
    at visit (/Users/matt/PhpstormProjects/test-project/node_modules/gulp-ng-annotate/node_modules/ng-annotate/node_modules/ordered-ast-traverse/ordered-ast-traverse.js:44:21)
    at visit (/Users/matt/PhpstormProjects/test-project/node_modules/gulp-ng-annotate/node_modules/ng-annotate/node_modules/ordered-ast-traverse/ordered-ast-traverse.js:41:25)

Process finished with exit code 1
```

**Comment by oblogic7** [comment]
Just figured this out.  Follow the instructions [https://github.com/Swiip/generator-gulp-angular/issues/347#issuecomment-76241019](here) carefully.  I tried this a couple of times and thought it wasn't working, but I was missing that I needed to change directories to `node_modules/gulp-ng-annotate/` and run the update command.

**Comment by swamper** [comment]
That did it oblogic7. Already had 0.15.1 in the package.json btw. I ran update inside gulp-ng-annotate and everything appears to be good on build and serve both now. I will remember to go deeper in the stack next time. I had builds failing all over the place regardless of what was installed at generation. Thanks much.
