### ISSUE TITLE
gulp test:auto not watching for changes

### ISSUE THREAD

**Issue by nowres** [Swiip/generator-gulp-angular#438]
Hello,

the task "test:auto" is not watching for file change, the Karma option autoWatch must be set to true to do so.

Here's what I put in gulp/unit-tests.js to get it working:

`karma.server.start({
        configFile: __dirname + '/../karma.conf.js',
        files: files,
        autoWatch: !singleRun,
        singleRun: singleRun
      }, done);`

**Comment by zckrs** [comment]
What version of generator you use ? What options you choose ?

**Comment by Swiip** [comment]
Strange, I thought I had test that. I remember I concluded that if I put nothing, the default was autoWatch true.

**Comment by nowres** [comment]
I use latest version 0.10.0, without autoWatch option, the tests are executed but used old sources.

**Comment by tb** [comment]
`gulp test:auto` reruns tests for `*.spec.js` changes, but not for `*.spec.coffee` changes.

**Comment by zckrs** [comment]
Because https://github.com/karma-runner/karma/blob/master/lib/config.js#L123 
We need to define autoWatch

**Comment by astw** [comment]
gulp test:auto  throws exception

C:\Users\bwang\icetrain\frontend_gulp_angular\gulp\unit-tests.js:39
          .concat(_.pluck(files, 'path'))
          ^
TypeError: Cannot read property 'concat' of undefined
    at C:\Users\bwang\icetrain\frontend_gulp_angular\gulp\unit-tests.js:39:11
    at ConcatStream.<anonymous> (C:\Users\bwang\icetrain\frontend_gulp_angular\node_modules\concat-stream\index.js:36:43)
    at ConcatStream.emit (events.js:129:20)
    at finishMaybe (C:\Users\bwang\icetrain\frontend_gulp_angular\node_modules\concat-stream\node_modules\readable-stream\lib\_stream_writable.js:460:14)
    at endWritable (C:\Users\bwang\icetrain\frontend_gulp_angular\node_modules\concat-stream\node_modules\readable-stream\lib\_stream_writable.js:469:3)
    at ConcatStream.Writable.end (C:\Users\bwang\icetrain\frontend_gulp_angular\node_modules\concat-stream\node_modules\readable-stream\lib\_stream_writable.js:436:5)
    at DestroyableTransform.onend (C:\Users\bwang\icetrain\frontend_gulp_angular\node_modules\gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:523:10)
    at DestroyableTransform.g (events.js:199:16)
    at DestroyableTransform.emit (events.js:129:20)
    at C:\Users\bwang\icetrain\frontend_gulp_angular\node_modules\gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:965:16
