### ISSUE TITLE
gulp test does not work once angultics is installed

### ISSUE THREAD

**Issue by lebsral** [Swiip/generator-gulp-angular#462]
Hi,

I have a project that has test fail whenever I add in angulartics.  
To demonstrate I created a new yeoman project. 
yo gulp-angular
 Karma tests worked fine. 
Then did just 
bower install angulartics --save

The gulp test fails

You can see for yourself here.
https://github.com/lebsral/ticsonly

Larss-MBP:ticsonly lars$ gulp test
[10:49:39] Using gulpfile ~/mycode/ticsonly/gulpfile.js
[10:49:39] Starting 'scripts'...
[10:49:39] all files 2.85 kB
[10:49:39] Finished 'scripts' after 374 ms
[10:49:39] Starting 'test'...
INFO [karma]: Karma v0.12.31 server started at http://localhost:9876/
INFO [launcher]: Starting browser PhantomJS
WARN [watcher]: Pattern "/Users/lars/mycode/ticsonly/src/**/*.mock.js" does not match any file.
INFO [PhantomJS 1.9.8 (Mac OS X)]: Connected on socket 4enTfAnMXLsyVQL6KufQ with id 52460829
PhantomJS 1.9.8 (Mac OS X) ERROR
  TypeError: 'undefined' is not a function (evaluating '$(window)')
  at /Users/lars/mycode/ticsonly/bower_components/waypoints/waypoints.js:25

[10:49:42] 'test' errored after 2.61 s
[10:49:42] Error: 1
    at formatError (/usr/local/lib/node_modules/gulp/bin/gulp.js:169:10)
    at Gulp.<anonymous> (/usr/local/lib/node_modules/gulp/bin/gulp.js:195:15)
    at Gulp.emit (events.js:107:17)
    at Gulp.Orchestrator._emitTaskDone (/Users/lars/mycode/ticsonly/node_modules/gulp/node_modules/orchestrator/index.js:264:8)
    at /Users/lars/mycode/ticsonly/node_modules/gulp/node_modules/orchestrator/index.js:275:23
    at finish (/Users/lars/mycode/ticsonly/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
    at cb (/Users/lars/mycode/ticsonly/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:29:3)
    at removeAllListeners (/Users/lars/mycode/ticsonly/node_modules/karma/lib/server.js:220:7)
    at Server.<anonymous> (/Users/lars/mycode/ticsonly/node_modules/karma/lib/server.js:231:9)
    at Server.g (events.js:199:16)

I'll cross post this to the angualtics (is there an official way to do that?)

**Comment by zckrs** [comment]
Sorry but I'm not reproduce your bug.
Can you try with master of generator ?

**Comment by lebsral** [comment]
To make this more simple I created this new clean setup.  The gulp test also fails here

https://github.com/lebsral/testvideo2

**Comment by BobbieBarker** [comment]
I am getting the same thing, except I do not have analytic s installed. 

I get this:
WARN [watcher]: Pattern "/Users/lars/mycode/ticsonly/src/*/.mock.js" does not match any file.
and I get this:
at formatError (/usr/local/lib/node_modules/gulp/bin/gulp.js:169:10)

Cept wtih a different file path.

**Comment by zckrs** [comment]
Fixed in master

**Comment by zckrs** [comment]
:tada: Just released v0.12.0 :tada:
Your issue should be fixed. I close but if you can retry your case with a new fresh install of generator you are welcome. Any feedback would be appreciated (positive comments too ^_^).
