### ISSUE TITLE
Error on yo gulp-angular with node v0.12.1

### ISSUE THREAD

**Issue by busches** [Swiip/generator-gulp-angular#464]
Executing `yo gulp-angular` or calling it through the `yo` menu results in the following error when ran with node v0.12.1 on Win7x64.

```
λ yo gulp-angular
C:\Users\buschs1\AppData\Roaming\npm\node_modules\generator-gulp-angular\node_modules\yeoman-generator\lib\base.js:445
  this.env.sharedFs.on('change', writeFiles);
                    ^
TypeError: undefined is not a function
    at run (C:\Users\buschs1\AppData\Roaming\npm\node_modules\generator-gulp-angular\node_modules\yeoman-generator\lib\base.js:445:21)
    at Environment.run (C:\Program Files\nodejs\node_modules\yo\node_modules\yeoman-environment\lib\environment.js:331:20)
    at C:\Program Files\nodejs\node_modules\yo\lib\cli.js:91:9
    at Environment.resolver.lookup (C:\Program Files\nodejs\node_modules\yo\node_modules\yeoman-environment\lib\resolver.js:50:12)
    at init (C:\Program Files\nodejs\node_modules\yo\lib\cli.js:66:7)
    at pre (C:\Program Files\nodejs\node_modules\yo\lib\cli.js:53:3)
    at Object.<anonymous> (C:\Program Files\nodejs\node_modules\yo\lib\cli.js:155:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
```
Running it with io.js v1.6.3 works as expected.

Other generators, gulp-ng and ng-poly, both work as expected with node v0.12.1.

**Comment by zckrs** [comment]
Can you try with other generator like generator-angular

**Comment by busches** [comment]
Whoops forgot to mention that, other generators are working fine, tried gulp-ng and ng-poly. I'll update the original issue.

**Comment by zckrs** [comment]
Not reproduce at moment.

With your output error log I'm not sure issue is related to this generator.

Can you try with node 0.12.2 ?

**Comment by busches** [comment]
Here's the output from running `yo gulp-ng` and then trying to run `yo gulp-angular`. I've also included node and yeoman versions.

````bash
λ node -v
v0.12.1

λ yo --version
1.4.5

λ mkdir test-gulp-ng && cd test-gulp-ng

C:\Users\buschs1\Desktop\test-gulp-ng
λ yo gulp-ng

     _-----_
    |       |
    |--(o)--|   .--------------------------.
   `---------´  |    Welcome to Yeoman,    |
    ( _´U`_ )   |   ladies and gentlemen!  |
    /___A___\   '__________________________'
     |  ~  |
   __'.___.'__
 ´   `  |° ´ Y `

This generator will generate a web app project using gulp, bower and angularjs.
   create app\app.css
   create app\app.js
   create app\app_controller.js
   create app\app_controller_test.js
   create app\index.html
   create app\components\app_service.js
   create app\components\app_service_test.js
   create app\main\main.html
   create app\main\main_controller.js
   create app\main\main_controller_test.js
   create .bowerrc
   create bower.json
   create gulpfile.js
   create package.json
   create karma-unit.js


I'm all done. Running bower install & npm install for you to install the required dependencies. If this fails, try running the command yourself.


^CTerminate batch job (Y/N)?
^C
C:\Users\buschs1\Desktop\test-gulp-ng
λ cd .. && mkdir test-gulp-angular2 && cd test-gulp-angular2

C:\Users\buschs1\Desktop\test-gulp-angular2
λ yo gulp-angular
C:\Users\buschs1\AppData\Roaming\npm\node_modules\generator-gulp-angular\node_modules\yeoman-generator\lib\base.js:445
  this.env.sharedFs.on('change', writeFiles);
                    ^
TypeError: undefined is not a function
    at run (C:\Users\buschs1\AppData\Roaming\npm\node_modules\generator-gulp-angular\node_modules\yeoman-generator\lib\base.js:445:21)
    at Environment.run (C:\Program Files\nodejs\node_modules\yo\node_modules\yeoman-environment\lib\environment.js:331:20)
    at C:\Program Files\nodejs\node_modules\yo\lib\cli.js:91:9
    at Environment.resolver.lookup (C:\Program Files\nodejs\node_modules\yo\node_modules\yeoman-environment\lib\resolver.js:50:12)
    at init (C:\Program Files\nodejs\node_modules\yo\lib\cli.js:66:7)
    at pre (C:\Program Files\nodejs\node_modules\yo\lib\cli.js:53:3)
    at Object.<anonymous> (C:\Program Files\nodejs\node_modules\yo\lib\cli.js:155:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
```

I will try with node 0.12.2-x64 in a bit.

**Comment by busches** [comment]
Same error on node v0.12.2-x64 on Win7, but I'm also able to get `yo ng-poly` to break now too. `yo gulp-ng` still works. Guessing it's an issue with `yeoman-generator` and I will open there.

```shell
C:\Users\buschs1\Desktop
λ node -v
v0.12.2

C:\Users\buschs1\Desktop
λ yo --version
1.4.5

C:\Users\buschs1\Desktop\test-gulp-angular2
λ yo gulp-angular
C:\Users\buschs1\AppData\Roaming\npm\node_modules\generator-gulp-angular\node_modules\yeoman-generator\lib\base.js:445
  this.env.sharedFs.on('change', writeFiles);
                    ^
TypeError: undefined is not a function
    at run (C:\Users\buschs1\AppData\Roaming\npm\node_modules\generator-gulp-angular\node_modules\yeoman-generator\lib\base.js:445:21)
    at Environment.run (C:\Program Files\nodejs\node_modules\yo\node_modules\yeoman-environment\lib\environment.js:331:20)
    at C:\Program Files\nodejs\node_modules\yo\lib\cli.js:91:9
    at Environment.resolver.lookup (C:\Program Files\nodejs\node_modules\yo\node_modules\yeoman-environment\lib\resolver.js:50:12)
    at init (C:\Program Files\nodejs\node_modules\yo\lib\cli.js:66:7)
    at pre (C:\Program Files\nodejs\node_modules\yo\lib\cli.js:53:3)
    at Object.<anonymous> (C:\Program Files\nodejs\node_modules\yo\lib\cli.js:155:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)

C:\Users\buschs1\Desktop\test-gulp-angular2
λ yo ng-poly
C:\Users\buschs1\AppData\Roaming\npm\node_modules\generator-ng-poly\node_modules\yeoman-generator\lib\base.js:445
  this.env.sharedFs.on('change', writeFiles);
                    ^
TypeError: undefined is not a function
    at run (C:\Users\buschs1\AppData\Roaming\npm\node_modules\generator-ng-poly\node_modules\yeoman-generator\lib\base.js:445:21)
    at Environment.run (C:\Program Files\nodejs\node_modules\yo\node_modules\yeoman-environment\lib\environment.js:331:20)
    at C:\Program Files\nodejs\node_modules\yo\lib\cli.js:91:9
    at Environment.resolver.lookup (C:\Program Files\nodejs\node_modules\yo\node_modules\yeoman-environment\lib\resolver.js:50:12)
    at init (C:\Program Files\nodejs\node_modules\yo\lib\cli.js:66:7)
    at pre (C:\Program Files\nodejs\node_modules\yo\lib\cli.js:53:3)
    at Object.<anonymous> (C:\Program Files\nodejs\node_modules\yo\lib\cli.js:155:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)

C:\Users\buschs1\Desktop\test-gulp-angular2
λ yo gulp-ng

     _-----_
    |       |
    |--(o)--|   .--------------------------.
   `---------´  |    Welcome to Yeoman,    |
    ( _´U`_ )   |   ladies and gentlemen!  |
    /___A___\   '__________________________'
     |  ~  |
   __'.___.'__
 ´   `  |° ´ Y `

This generator will generate a web app project using gulp, bower and angularjs.
```
