### ISSUE TITLE
Contributing - Tests Fail to Run

### ISSUE THREAD

**Issue by busches** [Swiip/generator-gulp-angular#503]
Checking out `master` and attempting to run `npm test` I get the following after a couple of minutes:

```
C:\Users\buschs1\Desktop\generator-gulp-angular (master)
λ npm test

> generator-gulp-angular@0.11.0 pretest C:\Users\buschs1\Desktop\generator-gulp-angular
> node test/template-cli.js prepare && node test/template-cli.js deps && cd test/tmp/deps && npm install && bow
er install

Compiling templates...
Done
Preparing dependencies description files...
Done
npm WARN package.json appName@0.0.0 No description
npm WARN package.json appName@0.0.0 No repository field.
npm WARN package.json appName@0.0.0 No README data
npm WARN package.json haml@0.4.3 No repository field.
npm WARN prefer global jshint@2.7.0 should be installed with -g

> generator-gulp-angular@0.11.0 test C:\Users\buschs1\Desktop\generator-gulp-angular
> mocha test/** -ig protractor

module.js:338
    throw err;
          ^
Error: Cannot find module 'C:\Users\buschs1\Desktop\generator-gulp-angular\test'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at C:\Users\buschs1\Desktop\generator-gulp-angular\node_modules\mocha\lib\mocha.js:184:27
    at Array.forEach (native)
    at Mocha.loadFiles (C:\Users\buschs1\Desktop\generator-gulp-angular\node_modules\mocha\lib\mocha.js:181:14)

    at Mocha.run (C:\Users\buschs1\Desktop\generator-gulp-angular\node_modules\mocha\lib\mocha.js:393:31)
    at Object.<anonymous> (C:\Users\buschs1\Desktop\generator-gulp-angular\node_modules\mocha\bin\_mocha:380:16
)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
npm ERR! Test failed.  See above for more details.
```

`npm install` and `bower install` ran without issue the first time as well.

Running node `v0.12.2` on Win7x64

**Comment by Swiip** [comment]
This should be about windows because it's work on my mac and in travis (linux)

**Comment by busches** [comment]
Yea, the more node I play with the most issues I have on Windows, that don't happen on our CI servers, which are linux.

**Comment by zckrs** [comment]
2 causes:
* the ** in cmd line
* mocha is not install globaly

**Comment by zckrs** [comment]
Should be fixed after https://github.com/Swiip/generator-gulp-angular/pull/554 merged

**Comment by busches** [comment]
Still failing after a while:

```
> generator-gulp-angular@0.11.0 test C:\Users\buschs1\Desktop\generator-gulp-angular
> mocha test/** -ig protractor

module.js:338
    throw err;
          ^
Error: Cannot find module 'C:\Users\buschs1\Desktop\generator-gulp-angular\test'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at C:\Users\buschs1\Desktop\generator-gulp-angular\node_modules\mocha\lib\mocha.js:192:27
    at Array.forEach (native)
    at Mocha.loadFiles (C:\Users\buschs1\Desktop\generator-gulp-angular\node_modules\mocha\lib\mocha.js:189:14)

    at Mocha.run (C:\Users\buschs1\Desktop\generator-gulp-angular\node_modules\mocha\lib\mocha.js:422:31)
    at Object.<anonymous> (C:\Users\buschs1\Desktop\generator-gulp-angular\node_modules\mocha\bin\_mocha:398:16
)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
npm ERR! Test failed.  See above for more details.
```

**Comment by zckrs** [comment]
In fact #554 don't fix. But we don't run generator test in Windows env. I'am not sure this feature is really useful. =\

**Comment by busches** [comment]
If you have no interest in contributions from windows users, then yes, this feature is not useful.

**Comment by zckrs** [comment]
I'm always interested by contribution. But we use TravisCI to test PR.
