### ISSUE TITLE
Broken test:auto task

### ISSUE THREAD

**Issue by nanocom** [Swiip/generator-gulp-angular#580]
When I install a fresh app, I get an exception when trying to launch test:auto

/home/arnaud/dev/kleinmallet-ui/gulp/unit-tests.js:30
          .concat(_.pluck(files, 'path'))
           ^
TypeError: Cannot call method 'concat' of undefined
    at /home/arnaud/dev/kleinmallet-ui/gulp/unit-tests.js:30:12
    at ConcatStream.<anonymous> (/home/arnaud/dev/kleinmallet-ui/node_modules/concat-stream/index.js:36:43)
    at ConcatStream.EventEmitter.emit (events.js:117:20)
    at finishMaybe (/home/arnaud/dev/kleinmallet-ui/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:460:14)
    at endWritable (/home/arnaud/dev/kleinmallet-ui/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:469:3)
    at ConcatStream.Writable.end (/home/arnaud/dev/kleinmallet-ui/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:436:5)
    at DestroyableTransform.onend (/home/arnaud/dev/kleinmallet-ui/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:523:10)
    at DestroyableTransform.g (events.js:180:16)
    at DestroyableTransform.EventEmitter.emit (events.js:117:20)
    at /home/arnaud/dev/kleinmallet-ui/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:965:16

**Comment by zckrs** [comment]
Duplicate https://github.com/Swiip/generator-gulp-angular/issues/497

**Comment by ismarslomic** [comment]
+1

**Comment by luxp** [comment]
I meet the same problem

**Comment by nanocom** [comment]
for folks who want to fix the problem quickly, just apply this fix manually: https://github.com/Swiip/generator-gulp-angular/pull/480

**Comment by zckrs** [comment]
:tada: Just released v0.12.0 :tada:
Your issue should be fixed. I close but if you can retry your case with a new fresh install of generator you are welcome. Any feedback would be appreciated (positive comments too ^_^).

**Comment by nanocom** [comment]
thx!
