### ISSUE TITLE
css file size is too large

### ISSUE THREAD

**Issue by tossp** [Swiip/generator-gulp-angular#754]
hi,
I generated from the less file CSS file size is too large, about 33000 lines. The csso plug-in  error:

```
Error: Please check the validity of the CSS block starting from the line #4511
    at throwError (/home/xxx/develop/tes_html/node_modules/gulp-csso/node_modules/csso/lib/gonzales.cssp.node.js:399:15)
    at getBlock (/home/xxx/develop/tes_html/node_modules/gulp-csso/node_modules/csso/lib/gonzales.cssp.node.js:755:18)
    at getRuleset (/home/xxx/develop/tes_html/node_modules/gulp-csso/node_modules/csso/lib/gonzales.cssp.node.js:1739:22)
    at getAtrulers (/home/xxx/develop/tes_html/node_modules/gulp-csso/node_modules/csso/lib/gonzales.cssp.node.js:705:31)
    at getAtruler (/home/xxx/develop/tes_html/node_modules/gulp-csso/node_modules/csso/lib/gonzales.cssp.node.js:663:22)
    at getAtrule (/home/xxx/develop/tes_html/node_modules/gulp-csso/node_modules/csso/lib/gonzales.cssp.node.js:605:28)
    at getStylesheet (/home/xxx/develop/tes_html/node_modules/gulp-csso/node_modules/csso/lib/gonzales.cssp.node.js:1937:60)
    at Object.CSSPRules.stylesheet (/home/xxx/develop/tes_html/node_modules/gulp-csso/node_modules/csso/lib/gonzales.cssp.node.js:365:69)
    at _getAST (/home/xxx/develop/tes_html/node_modules/gulp-csso/node_modules/csso/lib/gonzales.cssp.node.js:409:38)
    at /home/xxx/develop/tes_html/node_modules/gulp-csso/node_modules/csso/lib/gonzales.cssp.node.js:2287:16

```

**Comment by zckrs** [comment]
https://github.com/Swiip/generator-gulp-angular/issues/651 

CSSO is not maintened.
We use clean-css  via gulp-minify-css

**Comment by tossp** [comment]
Thank you very much
