### ISSUE TITLE
Error: Server terminated early with status 1

### ISSUE THREAD

**Issue by bradleyflood** [Swiip/generator-gulp-angular#853]
Fresh and unmodified installation of `generator-gulp-angular` on a new OSX machine today and am getting this error:

```
~/veromo/generator-gulp-angular:  gulp protractor
[17:16:51] Using gulpfile ~/veromo/generator-gulp-angular/gulpfile.js
[17:16:51] Starting 'scripts'...
[17:16:51] Starting 'styles'...
[17:16:51] Starting 'webdriver-update'...
Updating selenium standalone
downloading https://selenium-release.storage.googleapis.com/2.47/selenium-server-standalone-2.47.1.jar...
Updating chromedriver
downloading https://chromedriver.storage.googleapis.com/2.19/chromedriver_mac32.zip...
[17:16:52] gulp-inject 2 files into index.scss.
[17:16:52] Finished 'styles' after 1.07 s
[17:16:52] all files 13.93 kB
[17:16:52] Finished 'scripts' after 1.79 s
[17:16:52] Starting 'inject'...
[17:16:52] gulp-inject 1 files into index.html.
[17:16:52] gulp-inject 10 files into index.html.
[17:16:52] Finished 'inject' after 136 ms
[17:16:52] Starting 'serve:e2e'...
[17:16:53] Finished 'serve:e2e' after 56 ms
[BS] [BrowserSync SPA] Running...
[BS] Access URLs:
 ---------------------------------------
       Local: http://localhost:3000/
    External: http://10.131.226.34:3000/
 ---------------------------------------
          UI: http://localhost:3001
 UI External: http://10.131.226.34:3001
 ---------------------------------------
[BS] Serving files from: .tmp/serve
[BS] Serving files from: src
chromedriver_2.19.zip downloaded to /Users/bradleyflood/veromo/generator-gulp-angular/node_modules/gulp-protractor/node_modules/protractor/selenium/chromedriver_2.19.zip
selenium-server-standalone-2.47.1.jar downloaded to /Users/bradleyflood/veromo/generator-gulp-angular/node_modules/gulp-protractor/node_modules/protractor/selenium/selenium-server-standalone-2.47.1.jar
[17:17:18] Finished 'webdriver-update' after 27 s
[17:17:18] Starting 'protractor:src'...
Starting selenium standalone server...
[launcher] Running 1 instances of WebDriver
[launcher] Process exited with error code 1
/Users/bradleyflood/veromo/generator-gulp-angular/node_modules/gulp-protractor/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/async/nexttick.js:41
  goog.global.setTimeout(function() { throw exception; }, 0);
                                      ^

Error: Server terminated early with status 1
    at Error (native)
    at /Users/bradleyflood/veromo/generator-gulp-angular/node_modules/gulp-protractor/node_modules/protractor/node_modules/selenium-webdriver/remote/index.js:204:18
    at promise.ControlFlow.runInFrame_ (/Users/bradleyflood/veromo/generator-gulp-angular/node_modules/gulp-protractor/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:1857:20)
    at goog.defineClass.notify (/Users/bradleyflood/veromo/generator-gulp-angular/node_modules/gulp-protractor/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:2448:25)
    at promise.Promise.notify_ (/Users/bradleyflood/veromo/generator-gulp-angular/node_modules/gulp-protractor/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:564:12)
    at Array.forEach (native)
    at promise.Promise.notifyAll_ (/Users/bradleyflood/veromo/generator-gulp-angular/node_modules/gulp-protractor/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:553:15)
    at goog.async.run.processWorkQueue (/Users/bradleyflood/veromo/generator-gulp-angular/node_modules/gulp-protractor/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/async/run.js:130:15)
    at process._tickCallback (node.js:366:9)

/Users/bradleyflood/veromo/generator-gulp-angular/gulp/e2e-tests.js:27
      throw err;
      ^
Error: protractor exited with code 1
```
OSX 10.11. Latest versions of Node, Java, Etc.

Looks like [this guys is having the same issue on SO](http://stackoverflow.com/questions/33196337/gulp-protractor-selenium-webdriver-exited-status-1).

Would this be a selenium issue?

**Comment by Swiip** [comment]
Don't know about this problem. SO would lead to a problem with Selenium yes. I don't see a log about Chrome starting, does it open a window ?

**Comment by bradleyflood** [comment]
Nope no Chrome window opens. Am running latest Chrome 40.

**Comment by Swiip** [comment]
Hmm, i've got Chrome 46, can you try updating? Perhaps also something about tweeking the CHROME_BIN env value but it should be transparent...

**Comment by bradleyflood** [comment]
Problem solved -> According to the [gulp-protractor docs](https://github.com/mllrsohn/gulp-protractor) `protractor` is to be installed via `npm` along with `gulp-protractor` (instead of `protractor` as a dependency within `gulp-protractor`).

So I uninstalled `gulp-protractor`, `npm install --save-dev protractor` and then reinstalled `gulp-protractor` and the `gulp protractor` task works correctly now with no errors.

Could be a version requirement issue in `gulp-protractor`? Either way I think the `generator-gulp-angular` repo should have `protractor` as a dev dependency in the `package.json` -- what do you think?

**Comment by pedrodelgallego** [comment]
+1. I had the same issue. Adding protractor as a dep solved the problem

**Comment by theseanstewart** [comment]
I had the same issue, but @bradleyflood's solution didn't work for me. I ended up running the following commands and it started working again. 

```
brew update
brew cask install java
```
Source: https://github.com/angular/protractor/issues/2638#issuecomment-151986523

**Comment by XIXIAOSHI124** [comment]
I update protractor and gulp-protractor to the latest version, but it still cannot work. I follow @theseanstewart 's solution to update java from 1.7 to 1.8. protractor is working in my Mac now.
