### ISSUE TITLE
Misisng dependency "immutable" in "browser-sync"

### ISSUE THREAD

**Issue by DaAwesomeP** [Swiip/generator-gulp-angular#855]
When running `gulp` immediately after setting up the generator:
```
module.js:339
    throw err;
    ^

Error: Cannot find module 'immutable'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\path\to\project\node_modules\browser-sync\lib\hooks.js:4:20)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
```
Node v4.2.1 x64
NPM v2.7.5
Windows 8.1 Pro x64

**Comment by busches** [comment]
Attach your `yo-rc.json` file please. https://github.com/Swiip/generator-gulp-angular/blob/master/CONTRIBUTING.md#issues
