### ISSUE TITLE
Error after init project

### ISSUE THREAD

**Issue by idoo** [Swiip/generator-gulp-angular#950]
I had inited project with this generator and after `gulp serve` recived error

```
gulp serve                                                                                                                                                          17:25:11
module.js:329
    throw err;
    ^

Error: Cannot find module 'inherits'
    at Function.Module._resolveFilename (module.js:327:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:355:17)
    at require (internal/module.js:13:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/gulp/node_modules/through2/node_modules/readable-stream/lib/_stream_duplex.js:27:17)
    at Module._compile (module.js:399:26)
    at Object.Module._extensions..js (module.js:406:10)
    at Module.load (module.js:345:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:355:17)
```

**Comment by busches** [comment]
Please reference [how to create an issue](https://github.com/Swiip/generator-gulp-angular/blob/master/CONTRIBUTING.md#issues), so you can provide enough detail to get this resolved.
